language: rust

dist: bionic

arch:
  - amd64
  - arm64

before_install:
  - sudo apt-get update
  - sudo apt-get install musl-tools build-essential clang php-dev
  - ./helper-scripts/install-toolchain.sh

script:
  - ./helper-scripts/build.sh

services:
  - docker