language: rust

dist: jammy

arch:
  - amd64
  - arm64

before_install:
  - sudo apt-get update
  - sudo apt-get install musl-tools build-essential clang-11 php8.0-dev

script:
  - echo "Hello World!"
  - ./helper-scripts/build.sh

services:
  - docker