

dist: focal

arch:
  - amd64
  - arm64

services:
  - docker

os: linux

language: php

php:
  - 8.1

notifications:
  email:
    - team@appwrite.io

before_install:
  - >
    if [ ! -z "${DOCKERHUB_PULL_USERNAME:-}" ]; then
      echo "${DOCKERHUB_PULL_PASSWORD}" | docker login --username "${DOCKERHUB_PULL_USERNAME}" --password-stdin
    fi
install:
  - docker --version
  - composer install

script:
  - docker-compose up