language: rust

dist: focal

arch:
  - amd64
  - arm64

before_install:
  - sudo apt-get update
  - sudo apt-get install musl-tools build-essential clang-11 php-dev
  - ./helper-scripts/install-toolchain.sh

script:
  - ./helper-scripts/build.sh

services:
  - docker