language: rust
dist: bionic
arch:
- amd64

jobs:
  include:
    - env: BUILD_TARGET=amd64
    - env: BUILD_TARGET=arm64
    - env: BUILD_TARGET=armhf

before_install:
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo add-apt-repository "deb [arch=$TRAVIS_CPU_ARCH] https://download.docker.com/linux/ubuntu
  $(lsb_release -cs) stable"
- sudo apt-get update
- sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
- sudo docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
- sudo systemctl start docker
script:
- cargo vendor
- docker build --platform=linux/$BUILD_TARGET -t buildimage .
- docker create -t -i -v "$(pwd):/app" --platform=linux/$BUILD_TARGET --name=buildcontainer buildimage tail -f /dev/null
- docker start buildcontainer
- docker exec buildcontainer uname -m
- docker exec buildcontainer /bin/bash -c "cd /app && ./build.sh"
- mkdir -p target/release
- if [ "$BUILD_TARGET" = "arm64" ]; then sudo mv target/aarch64-unknown-linux-gnu/release/libphp_scrypt.so target/release/aarch64_libphp_scrypt.so && sudo mv target/aarch64-unknown-linux-musl/release/libphp_scrypt.so target/release/musl_aarch64_libphp_scrypt.so ; fi
- if [ "$BUILD_TARGET" = "amd64" ]; then sudo mv target/x86_64-unknown-linux-gnu/release/libphp_scrypt.so target/release/libphp_scrypt.so && sudo mv target/x86_64-unknown-linux-musl/release/libphp_scrypt.so target/release/musl_libphp_scrypt.so ; fi

services:
- docker

deploy:
  - provider: releases
    token:
      secure: mplF9LL7NQc2UFKepn7BhZ0LrEM/FmAG7OlRNqgiPQ8T8rw/vsWt88G/w1Yvjcm5KLdNC7M4BNOtNQiAwqPj/kMMONglWez/BOXr8j+w9g2l2xOgmopGTqxEJXWvB3sFrW8oP3kwqCBlBL7SG9Q5kW/lDU/aN5mD4BRPvgPgVhNaIvASVzyvP3K9YsId8UqRb6pfqbtaxPscX+t5ooClRK2DLpVnrPXAHMxqQli4Zi0e2gtj0Aw7AxbJKwwVhkyPshxw/VC/W0isUQ1ZV8qIZaQflJEeBy6XKW7PWwRU8xswM28Ee1BDsQOOnJyUE3kB7fT0llrBUNaFxXqWHydfv4W8sBL89wL/0GIEI9QigLUOnpmhW49uy+uVyN7HX78N+X/wGG5EKvZiYNPjroe2FUXV8+YAe+1DtuANgrjRIKkbL4eSg26WtshkvqhreMMVnZpQHO/Q5+Qc/t9LsNzTva97x6ovIRRCwn/4a1jUUGAbPWlN3N5ll/H6HnAxqX7NYRA6bsOQ/EIz+rHiTg7F9YTUTBCU2eXgEiWnuw/BOR4EUjJtMXYD++8ObmjgdTV7mt+iphWdddLsDxfye/gwdEwrR159gjA93hx7Q7czYDA1ye70PmMF3ghChHToN9Q6uWaL0NUiuVWSzOb98qme7XqyqHMy0KL2TJBU1L3Rju0=
    file: target/release/aarch64_libphp_scrypt.so
    on:
      repo: PineappleIOnic/php-scrypt
      branch: feat-add-github-actions
      condition: $BUILD_TARGET = arm64
    cleanup: 'false' 
  - provider: releases
    token:
      secure: mplF9LL7NQc2UFKepn7BhZ0LrEM/FmAG7OlRNqgiPQ8T8rw/vsWt88G/w1Yvjcm5KLdNC7M4BNOtNQiAwqPj/kMMONglWez/BOXr8j+w9g2l2xOgmopGTqxEJXWvB3sFrW8oP3kwqCBlBL7SG9Q5kW/lDU/aN5mD4BRPvgPgVhNaIvASVzyvP3K9YsId8UqRb6pfqbtaxPscX+t5ooClRK2DLpVnrPXAHMxqQli4Zi0e2gtj0Aw7AxbJKwwVhkyPshxw/VC/W0isUQ1ZV8qIZaQflJEeBy6XKW7PWwRU8xswM28Ee1BDsQOOnJyUE3kB7fT0llrBUNaFxXqWHydfv4W8sBL89wL/0GIEI9QigLUOnpmhW49uy+uVyN7HX78N+X/wGG5EKvZiYNPjroe2FUXV8+YAe+1DtuANgrjRIKkbL4eSg26WtshkvqhreMMVnZpQHO/Q5+Qc/t9LsNzTva97x6ovIRRCwn/4a1jUUGAbPWlN3N5ll/H6HnAxqX7NYRA6bsOQ/EIz+rHiTg7F9YTUTBCU2eXgEiWnuw/BOR4EUjJtMXYD++8ObmjgdTV7mt+iphWdddLsDxfye/gwdEwrR159gjA93hx7Q7czYDA1ye70PmMF3ghChHToN9Q6uWaL0NUiuVWSzOb98qme7XqyqHMy0KL2TJBU1L3Rju0=
    file: target/release/musl_aarch64_libphp_scrypt.so
    on:
      repo: PineappleIOnic/php-scrypt
      branch: feat-add-github-actions
      condition: $BUILD_TARGET = arm64
    cleanup: 'false' 
  - provider: releases
    token:
      secure: mplF9LL7NQc2UFKepn7BhZ0LrEM/FmAG7OlRNqgiPQ8T8rw/vsWt88G/w1Yvjcm5KLdNC7M4BNOtNQiAwqPj/kMMONglWez/BOXr8j+w9g2l2xOgmopGTqxEJXWvB3sFrW8oP3kwqCBlBL7SG9Q5kW/lDU/aN5mD4BRPvgPgVhNaIvASVzyvP3K9YsId8UqRb6pfqbtaxPscX+t5ooClRK2DLpVnrPXAHMxqQli4Zi0e2gtj0Aw7AxbJKwwVhkyPshxw/VC/W0isUQ1ZV8qIZaQflJEeBy6XKW7PWwRU8xswM28Ee1BDsQOOnJyUE3kB7fT0llrBUNaFxXqWHydfv4W8sBL89wL/0GIEI9QigLUOnpmhW49uy+uVyN7HX78N+X/wGG5EKvZiYNPjroe2FUXV8+YAe+1DtuANgrjRIKkbL4eSg26WtshkvqhreMMVnZpQHO/Q5+Qc/t9LsNzTva97x6ovIRRCwn/4a1jUUGAbPWlN3N5ll/H6HnAxqX7NYRA6bsOQ/EIz+rHiTg7F9YTUTBCU2eXgEiWnuw/BOR4EUjJtMXYD++8ObmjgdTV7mt+iphWdddLsDxfye/gwdEwrR159gjA93hx7Q7czYDA1ye70PmMF3ghChHToN9Q6uWaL0NUiuVWSzOb98qme7XqyqHMy0KL2TJBU1L3Rju0=
    file: target/release/libphp_scrypt.so
    on:
      repo: PineappleIOnic/php-scrypt
      branch: feat-add-github-actions
      condition: $BUILD_TARGET = amd64
    cleanup: 'false' 
  - provider: releases
    token:
      secure: mplF9LL7NQc2UFKepn7BhZ0LrEM/FmAG7OlRNqgiPQ8T8rw/vsWt88G/w1Yvjcm5KLdNC7M4BNOtNQiAwqPj/kMMONglWez/BOXr8j+w9g2l2xOgmopGTqxEJXWvB3sFrW8oP3kwqCBlBL7SG9Q5kW/lDU/aN5mD4BRPvgPgVhNaIvASVzyvP3K9YsId8UqRb6pfqbtaxPscX+t5ooClRK2DLpVnrPXAHMxqQli4Zi0e2gtj0Aw7AxbJKwwVhkyPshxw/VC/W0isUQ1ZV8qIZaQflJEeBy6XKW7PWwRU8xswM28Ee1BDsQOOnJyUE3kB7fT0llrBUNaFxXqWHydfv4W8sBL89wL/0GIEI9QigLUOnpmhW49uy+uVyN7HX78N+X/wGG5EKvZiYNPjroe2FUXV8+YAe+1DtuANgrjRIKkbL4eSg26WtshkvqhreMMVnZpQHO/Q5+Qc/t9LsNzTva97x6ovIRRCwn/4a1jUUGAbPWlN3N5ll/H6HnAxqX7NYRA6bsOQ/EIz+rHiTg7F9YTUTBCU2eXgEiWnuw/BOR4EUjJtMXYD++8ObmjgdTV7mt+iphWdddLsDxfye/gwdEwrR159gjA93hx7Q7czYDA1ye70PmMF3ghChHToN9Q6uWaL0NUiuVWSzOb98qme7XqyqHMy0KL2TJBU1L3Rju0=
    file: target/release/musl_libphp_scrypt.so
    on:
      repo: PineappleIOnic/php-scrypt
      branch: feat-add-github-actions
      condition: $BUILD_TARGET = amd64
    cleanup: 'false' 
