language: rust

dist: jammy

arch:
  - amd64
  - arm64

before_install:
  - sudo apt-get update
  - docker build --platform=linux/$TRAVIS_CPU_ARCH -t buildimage .
  - docker create -t -i -v "$(pwd):/app" --platform=linux/amd64 --name=buildcontainer buildimage tail -f /dev/null
  - docker start buildcontainer

script:
  - docker exec buildcontainer sh -c "cd /app && /scripts/build.sh"

services:
  - docker