[build]
xargo = false
build-std = false
default-target = "x86_64-unknown-linux-gnu"
pre-build = ["apt install software-properties-common && add-apt-repository ppa:ondrej/php && apt update && apt install php8.0"] # can also be the path to a file to run