name: Build Release

on: push

env:
  CARGO_TERM_COLOR: always


jobs:
  build:
  runs-on: ubuntu-latest
  name: Build Releases X86_64
  steps:
    - uses: actions/checkout@v3
    - name: Install PHP
      uses: nanasess/setup-php@v3
      with: 
        php-version: '8.0'
    - name: Install Rust Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        target: x86_64-unknown-linux-gnu, x86_64-pc-windows-gnu, x86_64-apple-darwin
    - name: Build Extension
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --target x86_64-unknown-linux-gnu, x86_64-pc-windows-gnu, x86_64-apple-darwin