name: Build Release
on: [push]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Releases X86_64
    steps:
      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: 'x86_64-unknown-linux-gnu, x86_64-pc-windows-gnu, x86_64-apple-darwin'
      - name: Build Extension (Linux GNU)
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target x86_64-unknown-linux-gnu
          use-cross: false
      - name: Build Extension (Windows GNU)
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target x86_64-pc-windows-gnu
          use-cross: true
      - name: Build Extension (MacOS X86_64)
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target x86_64-apple-darwin
          use-cross: true