name: Build Release
on: [push]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Linux Releases X86_64
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: 'x86_64-unknown-linux-gnu, x86_64-unknown-linux-musl'
      - name: Install Dependencies
        run: sudo apt-get install musl-tools build-essential clang-11 php8.0-dev
      - name: Build Extension (Linux GNU)
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target x86_64-unknown-linux-gnu
          use-cross: false
      - name: Build Extension (Alpine musl)
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target x86_64-unknown-linux-musl
          use-cross: false
      - uses: actions/upload-artifact@v3
        with:
          name: GNU Linux (x86_64)
          path: target/x86_64-unknown-linux-gnu/release/libphp_scrypt.so
      - uses: actions/upload-artifact@v3
        with:
          name: Alpine Linux (x86_64)
          path: target/x86_64-unknown-linux-musl/release/libphp_scrypt.so